version: "3.5"

services:
  back:
    container_name: property_back
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ".db.env"
      - ".back.env"
